title: "Sam & Moore"
email: me@samandmoore.com
description: >
  Hi there! This is the personal website of Sam Moore. I'm software maker
  in New York City. I enjoy reading, cooking & making cocktails with my wife
  Laura, playing with my doggo Hazel, and my kiddos.
baseurl: ""
url: "https://samandmoore.com"
twitter_username: samandmoore
github_username: samandmoore

markdown: kramdown

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - Rakefile

destination: _site
