title: "Sam & Moore"
email: me@samandmoore.com
description: >
  Hi there! This is the personal website of Sam Moore. I am a software maker
  living and working in New York City. I enjoy reading, cooking & making
  cocktails with Laura, and playing with my doggo Hazel.
baseurl: ""
url: "https://samandmoore.com"
twitter_username: samandmoore
github_username:  samandmoore

markdown: kramdown

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - Rakefile

destination: _site
